In [1]:
import numpy as np
simple_list=[6,7,8]
np.array(simple_list)

array([6, 7, 8])

In [3]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
list_of_lists=[1,2,3],[4,5,6],[7,8,9]
np.array(list_of_lists)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.arange(5,23)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22])

In [7]:
np.arange(2,36,5)

array([ 2,  7, 12, 17, 22, 27, 32])

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(4)

array([1., 1., 1., 1.])

In [13]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [16]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [19]:
np.eye(5,dtype=float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(2,4)

array([[0.44380732, 0.20112366, 0.49022147, 0.55925517],
       [0.98812614, 0.15317898, 0.31171209, 0.58643891]])

In [27]:
np.random.randn(2,4)

array([[-0.56824678, -0.48850304,  0.90632064, -0.68605809],
       [ 0.14064177,  0.82362639,  1.09640173, -0.39788696]])

In [34]:
np.random.randint(2,9)

4

In [40]:
np.random.randint(20,56,100)

array([25, 20, 29, 44, 45, 30, 22, 39, 34, 21, 32, 33, 38, 51, 24, 27, 21,
       32, 27, 21, 36, 35, 55, 53, 25, 24, 53, 23, 24, 36, 32, 32, 29, 35,
       30, 54, 30, 40, 33, 39, 46, 34, 24, 35, 48, 52, 51, 38, 47, 36, 28,
       43, 39, 29, 48, 34, 49, 51, 26, 37, 42, 27, 50, 52, 34, 31, 23, 22,
       50, 23, 48, 36, 54, 47, 36, 32, 52, 54, 47, 32, 54, 36, 25, 42, 54,
       49, 38, 46, 27, 22, 38, 26, 38, 52, 28, 46, 20, 41, 49, 26])

In [42]:
sample_array=np.arange(2,20)
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [43]:
rand_array=np.random.randint(0,10,5)
rand_array

array([2, 7, 9, 9, 4])

In [44]:
sample_array.min()

2

In [46]:
rand_array.argmin()

0

In [47]:
rand_array.max()

9

In [48]:
sample_array.argmax()

17

In [49]:
sample_array

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [50]:
sample_array.dtype

dtype('int64')

In [54]:
a=np.eye((5),dtype=int)
a

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [55]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [56]:
B=np.random.rand(2,3)
B

array([[0.89475583, 0.61496218, 0.42115009],
       [0.76176788, 0.54919404, 0.15162199]])

In [57]:
a.T

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [58]:
B.T

array([[0.89475583, 0.76176788],
       [0.61496218, 0.54919404],
       [0.42115009, 0.15162199]])

In [61]:
import numpy as np
sample_array=np.arange(10,22)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21])

In [68]:
sample_array=sample_array.reshape(6,2)
sample_array

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21]])

In [69]:
sample_array[4:]

array([[18, 19],
       [20, 21]])

In [76]:
sample_array[0]=100
sample_array[1]=2
sample_array

array([[100, 100],
       [  2,   2],
       [ 14,  15],
       [ 16,  17],
       [ 18,  19],
       [ 20,  21]])

In [79]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [80]:
sample_array[0:10]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
sample_array[:]=1
sample_array 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])